### ISSUE TITLE
How to Save at a particular Size?

### ISSUE THREAD

**Issue by Al-Fol** [Si13n7/ImageToIcon#4]
When saving the ico, it defaults to 16x16px. I'd like my file to be 256x256px. How do you do that, please? It's not clear. When I click on the 256px box, I get pinged to my last folder to select an image for conversion - so I'm going round in circles.

Looks like a good little tool but no instructions found. Thanks for any help.

**Comment by Si13n7** [comment]
Icon sizes are automatically determined based on the specified image.

For example, if you open a small image less than 20x20px, it will only create a 16x16px icon with no other sizes. It makes sense to create a 256x256px icon from such a small image because the loss of quality would be ridiculously high and it would just look crappy anyway.

Therefore, you should directly try adding large images to get all the sizes you need. You can then also exchange individual icons of different sizes if you want some icons to look different or if you are dissatisfied with the quality.
